[package]
name = "os"
version = "0.1.0"
authors = ["罗境佳 <luojj18@mails.tsinghua.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
riscv = { git = "ssh://git@github.com/rcore-os/riscv.git", features = ["inline-asm"] }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
